account: LU1832
theme: dark           # white, dark
host: '127.0.0.1'
port: 7497
client_id: 0
#-------------- active strategies -------------#
strategy:
  MovingAverageCrossStrategy:
    patth: None
    active: False
    capital: 10000
    params:
      short_window: 20
      long_window: 80
    symbols:
      - SPY STK SMART
      - AAPL STK SMART
      - AMZN STK SMART
  BuyAndHoldStrategy:
    patth: None
    active: False
    params:
      ticks: 5
    symbols:
      - SPY STK SMART
      - AMZN STK SMART
      - MSFT STK SMART
  OrderPerIntervalStrategy:
    path: 'd:/workspace/quanttrading2/examples/order_per_interval_strategy.py'
    active: True
    capital: 50000
    params:
      tick_trigger_threshold: 50
      tick_trigger_threshold2: 100
    symbols:
      - SPY STK SMART
      - AAPL STK SMART
      - AMZN STK SMART
      - ESU0 FUT GLOBEX
      - CLU0 FUT NYMEX
      - NGU0 FUT NYMEX