account: LU1832
theme: dark           # white, dark
host: '127.0.0.1'
port: 7497
client_id: 0
log_path: 'd:/workspace/log/'
#-------------- active strategies -------------#
strategy:
  MovingAverageCrossStrategy:
    path: 'd:/workspace/quanttrading2/examples/moving_average_cross_strategy.py'
    active: False
    capital: 10000
    params:
      G: 20
    symbols:
      - CLV0 FUT NYMEX 1000
  BuyAndHoldStrategy:
    path: None
    active: False
    params:
      ticks: 5
      tick_trigger_threshold: 5000
    symbols:
      - SPY STK SMART
      - AMZN STK SMART
      - MSFT STK SMART
  OrderPerIntervalStrategy:
    path: 'd:/workspace/quanttrading2/examples/order_per_interval_strategy.py'
    active: False
    capital: 50000
    params:
      tick_trigger_threshold: 50
    symbols:
      #- SPY STK SMART
      #- AAPL STK SMART
      #- AMZN STK SMART
      - ESU0 FUT GLOBEX 50
      - CLV0 FUT NYMEX 1000
      - NGV0 FUT NYMEX 10000