account: LU1832
theme: dark           # white, dark
host: '127.0.0.1'
port: 7497
client_id: 0

#-------------- active strategies -------------#
strategy:
  MovingAverageCrossStrategy:
    active: False
    capital: 10000
    params:
      G: 20
    symbols:
      - CLV0 FUT NYMEX 1000
  OrderPerIntervalStrategy:
    active: False
    capital: 50000
    params:
      tick_trigger_threshold: 500
    symbols:
      #- SPY STK SMART
      #- AAPL STK SMART
      #- AMZN STK SMART
      - ESU0 FUT GLOBEX 50
      #- CLV0 FUT NYMEX 1000
      #- NGV0 FUT NYMEX 10000