account: LU1832
theme: dark           # white, dark
host: '127.0.0.1'
port: '7497'
client_id: 0
#-------------- active strategies -------------#
strategy:
  MovingAverageCrossStrategy:
    short_window: 20
    long_window: 80
    symbols:
      - SPY STK SMART
      - AAPL STK SMART
      - AMZN STK SMART
  BuyAndHoldStrategy:
    ticks: 5
    symbols:
      - SPY STK SMART
      - AMZN STK SMART
      - MSFT STK SMART
  OrderPerIntervalStrategy:
    tick_trigger_threshold: 50
    symbols:
      - IC1802
      - IF1802